## Kubetail CLI Configuration
#

## version ##
#
# Sets the version of the config schema
#
# Default value: 1
#
version: 1

## kubeconfig ##
#
# Overrides the default kubeconfig path ($HOMEDIR/.kube/config)
#
# Default value: __empty__
#
kubeconfig:

## context ##
#
# Overrides the default context defined in kubeconfig
#
# Default value: __empty__
#
context:

## logs ##
#
logs:

  ## head ##
  #
  # Sets the default number of log records to return for `head`
  #
  # Default value: 10
  #
  head: 10

  ## tail ##
  #
  # Sets the default number of log records to return for `tail`
  #
  # Default value: 10
  #
  tail: 10

  ## columns ##
  #
  # Sets the default columns to show when displaying log records
  #
  # Default value: [ts, dot, message]
  #
  columns:
    - ts
    - dot
    - message

## serve ##
#
serve:

  ## port ##
  #
  # The port to use for the dashboard server
  # 
  # Default: 7500
  #
  port: 7500

  ## theme ##
  #
  # Default value: system
  #
  # One of:
  #   - system
  #   - light
  #   - dark
  # 
  theme: system

  ## columns ##
  #
  # Sets the default columns to show when displaying log records
  #
  # Default value: [ts, dot, message]
  #
  columns:
    - ts
    - dot
    - message

## custom-filters ##
#
custom-filters:

  ## <filter-name> ##
  #
  # Sets variables for a custom filter
  #
  <filter-name>:

## custom-parsers ##
#
custom-parsers:

  ## <parser-name> ##
  #
  # Sets variables for a custom parser
  #
  <parser-name>:

## custom-formatter ##

  ## <formatter-name> ##
  #
  # Sets variables for a custom formatter
  #
  <formatter-name>:

## profiles ##
#
profiles:

  ## <profile-name> ##
  #
  # Sets config variables for a custom profile 
  #
  <profile-name>:
